# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-17 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.RemoveField(
            model_name='image',
            name='users_like',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
